version: '3'

services:

  nginx:
    image: nginx:latest 
    container_name: nginx
    restart: always 
    volumes:
      - ./frontend/dist:/app:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    ports:
      - "80:80"
